export const BOOK_LIST_REQUEST="BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS="BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL="BOOK_LIST_FAIL";

export const BOOK_ADD_REQUEST="BOOK_ADD_REQUEST";
export const BOOK_ADD_SUCCESS="BOOK_ADD_SUCCESS";
export const BOOK_ADD_FAIL="BOOK_ADD_FAIL";

export const BOOK_UPD_REQUEST="BOOK_UPD_REQUEST";
export const BOOK_UPD_SUCCESS="BOOK_UPD_SUCCESS";
export const BOOK_UPD_FAIL="BOOK_UPD_FAIL";

export const BOOK_GETBYID_REQUEST="BOOK_GETBYID_REQUEST";
export const BOOK_GETBYID_SUCCESS="BOOK_GETBYID_SUCCESS";
export const BOOK_GETBYID_FAIL="BOOK_GETBYID_FAIL";

export const BOOK_DEL_REQUEST="BOOK_DEL_REQUEST";
export const BOOK_DEL_SUCCESS="BOOK_DEL_SUCCESS";
export const BOOK_DEL_FAIL="BOOK_DEL_FAIL";
